<?php

/**
 * Created by PhpStorm.
 * User: mkkn
 * Date: 2016/05/14
 * Time: 4:40
 */
class FileStorageTest extends TestCase
{
    /** @var  \Chatbox\Upload\Entity\Storage\FileStorage */
    protected $service;

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->service = app(\Chatbox\Upload\Entity\Storage\FileStorage::class);
    }


    /**
     * @test
     */
    public function testStore(){
        $file = new \Symfony\Component\HttpFoundation\File\File("/Users/mkkn/Downloads/gfo_logo.png");
        $key = \Illuminate\Support\Str::random();
        $this->service->store($key,$file);



    }

}